# Mean field approximation

$$ H = t\sum_{i\sigma}\left( c^{\dagger}_{i\sigma}c_{i+1\sigma} + c^{\dagger}_{i+1\sigma}c_{i\sigma} \right) + U\sum_i c^{\dagger}_{i\uparrow}c_{i\uparrow}c^{\dagger}_{i\downarrow}c_{i\downarrow}$$

$$ H_{\text{mean-field}} = t\sum_{i\sigma}\left( c^{\dagger}_{i\sigma}c_{i+1\sigma} + c^{\dagger}_{i+1\sigma}c_{i\sigma} \right) + U\sum_i \left( <n_{\downarrow}>c^{\dagger}_{i\uparrow}c_{i\uparrow} + <n_{\uparrow}>c^{\dagger}_{i\downarrow}c_{i\downarrow} - <n_{\uparrow}><n_{\downarrow}>\right) $$

In [20]:
import numpy as np

## Single particle representation

Becuase the mean-field Hamiltonian does not couple fermions, we can start in the single particle basis then build up the rest of the energy levels by simply adding the single particle levels together.

In [34]:
N = 4
n_avg = 0.5
U = 0.0
mu = U*(n_avg - n_avg**2)
t = -1.0
H = [[0 for i in range(0,2*N)] for j in range(0,2*N)]
for i in range(0,N):
    H[i][i] = mu
    H[i+N][i+N] = mu
    H[i][np.mod(i+1,N)] = t
    H[np.mod(i+1,N)][i] = t
    H[i+N][np.mod(i+1,N)+N] = t
    H[np.mod(i+1,N)+N][i+N] = t

In [35]:
e,y = np.linalg.eig(H)
np.sort(e)

array([-2.00000000e+00, -2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        6.59737022e-17,  6.59737022e-17,  2.00000000e+00,  2.00000000e+00])

In [36]:
def E(n):
    return mu + 2*t*np.cos(2*n*np.pi/N)

for n in range(N):
    print(E(n))

-2.0
-1.2246467991473532e-16
2.0
3.6739403974420594e-16


## Compare to the full Hamiltonian

If $\{E_i\}$ are the single particle mean-field enegy levels then the two particle mean field levels are $\{E_i + E_j\}$ and the three particle states are $\{E_i + E_j + E_k\}$ for $i \neq j \neq k$ ect... 

For U = 0 the mean-field energy levels are the same as the full many-body energy levels.

In [37]:
# A function to print out the binary number
def bi(num,S):
    bi = bin(num)
    out = []
    Sdiff = S - len(bi) + 2
    for i in range(0,Sdiff):
        out.append(0)
    for i in range(2,len(bi)):
        out.append(int(bi[i]))
    return out

E_full = []
for n in range(0,2**(2*N)):
    state = bi(n,2*N)
    E = np.dot(state,e)
    E_full.append(E)
np.sort(E_full)

array([-4.00000000e+00, -4.00000000e+00, -4.00000000e+00, -4.00000000e+00,
       -4.00000000e+00, -4.00000000e+00, -4.00000000e+00, -4.00000000e+00,
       -4.00000000e+00, -4.00000000e+00, -4.00000000e+00, -4.00000000e+00,
       -4.00000000e+00, -4.00000000e+00, -4.00000000e+00, -4.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -2.00000000e+00, -2.00000000e+00, -2.00000000e+00,
       -2.00000000e+00, -

In [38]:
import qiskit.quantum_info as qi

def X_label(i,Q):
    out = ''
    for j in range(0,Q):
        if i < Q-1:
            if i == j or i + 1 == j:
                out = out + 'X'
            else:
                out = out + 'I'
        else:
            if j == 0 or j == Q-1:
                out = out + 'X'
            else:
                out = out + 'Z'
    return out[::-1]

def Y_label(i,Q):
    out = ''
    for j in range(0,Q):
        if i < Q-1:
            if i == j or i + 1 == j:
                out = out + 'Y'
            else:
                out = out + 'I'
        else:
            if j == 0 or j == Q-1:
                out = out + 'Y'
            else:
                out = out + 'Z'
    return out[::-1]

def I_label(Q):
    out = ''
    for j in range(Q):
        out = out + 'I'
    return out

def Z_label(i,Q):
    out = ''
    for j in range(0,Q):
        if j == i:
            out = out + 'Z'
        else:
            out = out + 'I'
    return out[::-1]


H_mb = 0*qi.Operator.from_label(I_label(2*N))
for i in range(0,N):
    H_mb = H_mb + 1/2*t*qi.Operator.from_label( X_label(i,N) + I_label(N) )
    H_mb = H_mb + 1/2*t*qi.Operator.from_label( Y_label(i,N) + I_label(N) )
    H_mb = H_mb + 1/2*t*qi.Operator.from_label( I_label(N) + X_label(i,N) )
    H_mb = H_mb + 1/2*t*qi.Operator.from_label( I_label(N) + Y_label(i,N) )
    H_mb = H_mb + 1/4*U*qi.Operator.from_label( Z_label(i,N) + Z_label(i,N) )
    H_mb = H_mb + 1/4*U*qi.Operator.from_label( Z_label(i,N) + I_label(N) )
    H_mb = H_mb + 1/4*U*qi.Operator.from_label( I_label(N) + Z_label(i,N) )
    H_mb = H_mb + 1/4*U*qi.Operator.from_label( I_label(N) + I_label(N) )
    
    

In [39]:
e_mb,y_mb = np.linalg.eig(H_mb.data)

np.sort(e_mb)

array([-4.00000000e+00+3.63615565e-31j, -4.00000000e+00+3.63591769e-31j,
       -4.00000000e+00+2.85654807e-31j, -4.00000000e+00-1.31483059e-31j,
       -4.00000000e+00+1.52461667e-31j, -4.00000000e+00-3.14165278e-31j,
       -4.00000000e+00+1.60165636e-31j, -4.00000000e+00-7.52397761e-34j,
       -4.00000000e+00+2.61731061e-33j, -4.00000000e+00+1.95463443e-31j,
       -4.00000000e+00+3.79780527e-32j, -4.00000000e+00-7.25312978e-32j,
       -4.00000000e+00-2.44822451e-31j, -4.00000000e+00-8.53022704e-32j,
       -4.00000000e+00-2.59888287e-31j, -4.00000000e+00+2.38406594e-32j,
       -2.00000000e+00+7.25750212e-34j, -2.00000000e+00-3.95859190e-31j,
       -2.00000000e+00+8.88816669e-32j, -2.00000000e+00-2.46519033e-32j,
       -2.00000000e+00+4.39311326e-32j, -2.00000000e+00-2.46458078e-31j,
       -2.00000000e+00+6.90410102e-31j, -2.00000000e+00-3.94430453e-31j,
       -2.00000000e+00-3.91736370e-31j, -2.00000000e+00-1.96894500e-31j,
       -2.00000000e+00+2.44978289e-31j, -2.00000000

## Compare to spin restricted Hamiltonian

In [40]:
import numpy as np

u=0
t=-1


H = np.load('/Users/stenger/Documents/Research/Hubbard_symmetries/VQE/H_mu_'+str(u)+"_t_"+str(t)+'.npy')
e,y = np.linalg.eig(H)

In [41]:
np.sort(e)

array([-4.00000000e+00+0.00000000e+00j, -4.00000000e+00+0.00000000e+00j,
       -4.00000000e+00+0.00000000e+00j, -4.00000000e+00+0.00000000e+00j,
       -2.00000000e+00+0.00000000e+00j, -2.00000000e+00+0.00000000e+00j,
       -2.00000000e+00+0.00000000e+00j, -2.00000000e+00+0.00000000e+00j,
       -2.00000000e+00+0.00000000e+00j, -2.00000000e+00+0.00000000e+00j,
       -2.00000000e+00+0.00000000e+00j, -2.00000000e+00+0.00000000e+00j,
       -1.79535360e-16+0.00000000e+00j, -1.70216296e-16+0.00000000e+00j,
       -1.61812771e-16+0.00000000e+00j, -3.55773415e-17+0.00000000e+00j,
       -2.18015587e-17-1.29000861e-16j, -2.18015587e-17+1.29000861e-16j,
        3.57259426e-17-2.04654417e-16j,  3.57259426e-17+2.04654417e-16j,
        1.34561858e-16+0.00000000e+00j,  3.17067822e-16+0.00000000e+00j,
        3.40097149e-16+0.00000000e+00j,  6.82375074e-16+0.00000000e+00j,
        2.00000000e+00+0.00000000e+00j,  2.00000000e+00+0.00000000e+00j,
        2.00000000e+00+0.00000000e+00j,  2.00000000

In [42]:
pwd

'/Users/stenger/Documents/Research/Hubbard_symmetries'