# Decomposing the Heisenberg model using symmeteries

## Following https://arxiv.org/pdf/1101.3281.pdf

In [1]:
from qiskit import quantum_info as qi
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.1f}'.format

In [2]:
def I0(L):
    label = ""
    for i in range(0,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sx(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "X"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sy(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "Y"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sz(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "Z"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data
    
def Sp(l,L):
    return Sx(0,L)+Sy(0,L)

def Sm(l,L):
    return Sx(0,L)-Sy(0,L)

In [3]:
def H(Jx,Jy,Jz,L):
    h=0
    for i in range(0,L-1):
        h+= Jx*np.dot(Sz(i,L),Sz(i+1,L))
        h+= Jy*np.dot(Sx(i,L),Sx(i+1,L))
        h+= Jz*np.dot(Sy(i,L),Sy(i+1,L))
    h+= Jx*np.dot(Sz(L-1,L),Sz(0,L))
    h+= Jy*np.dot(Sx(L-1,L),Sx(0,L))
    h+= Jz*np.dot(Sy(L-1,L),Sy(0,L))
    return h
        

In [4]:
H(1,1,1,2)

array([[ 2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -2.+0.j,  4.+0.j,  0.+0.j],
       [ 0.+0.j,  4.+0.j, -2.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  2.+0.j]])

In [5]:
pd.DataFrame(Sz(2,3))

0         1        2         3        4         5        6         7
0 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
1 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
2 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
3 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
4 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
5 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j
6 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j
7 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j

In [6]:
pd.DataFrame(Sz(0,3))

0        1        2        3         4         5         6         7
0 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
1 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
2 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
4 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j

In [7]:
pd.DataFrame(Sx(0,3))

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j
4 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [8]:
these = 1/2*(I0(3)-np.dot(Sz(0,3),Sz(2,3)))
pd.DataFrame(these)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
4 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [9]:
flip = np.dot(Sx(0,3),Sx(2,3))
pd.DataFrame(flip)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [10]:
swap = np.dot(flip,these)
pd.DataFrame(swap)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [11]:
keep = 1/2*(I0(3)+np.dot(Sz(0,3),Sz(2,3)))
pd.DataFrame(keep+swap)

0        1        2        3        4        5        6        7
0 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j

In [12]:
def Exchange(i,j,L):
    change = 1/2*(I0(L)-np.dot(Sz(i,L),Sz(j,L)))
    keep = 1/2*(I0(L)+np.dot(Sz(i,L),Sz(j,L)))
    flip = np.dot(Sx(i,L),Sx(j,L))
    swap = np.dot(flip,change)
    return keep+swap
    

In [13]:
#Translation Operator
def T(L):
    t = I0(L)
    for i in range(0,L-1):
        exc = Exchange(L-2-i,L-1-i,L)
        t = np.dot(exc,t)
    return t

### Below I do a bunch of tests of the translation operator

In [14]:
pd.DataFrame(H(1,1,1,3))

0         1         2         3         4         5         6  \
0 3.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
1 0.0+0.0j -1.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
2 0.0+0.0j  2.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
3 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  2.0+0.0j   
4 0.0+0.0j  2.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j   
5 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  2.0+0.0j   
6 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j -1.0+0.0j   
7 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   

         7  
0 0.0+0.0j  
1 0.0+0.0j  
2 0.0+0.0j  
3 0.0+0.0j  
4 0.0+0.0j  
5 0.0+0.0j  
6 0.0+0.0j  
7 3.0+0.0j

In [15]:
pd.DataFrame(np.dot(T(3),np.dot(H(1,1,1,3),np.transpose(T(3)))))

0         1         2         3         4         5         6  \
0 3.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
1 0.0+0.0j -1.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
2 0.0+0.0j  2.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
3 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  2.0+0.0j   
4 0.0+0.0j  2.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j   
5 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  2.0+0.0j   
6 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j -1.0+0.0j   
7 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   

         7  
0 0.0+0.0j  
1 0.0+0.0j  
2 0.0+0.0j  
3 0.0+0.0j  
4 0.0+0.0j  
5 0.0+0.0j  
6 0.0+0.0j  
7 3.0+0.0j

In [16]:
H(1,1,1,3)-np.dot(T(3),np.dot(H(1,1,1,3),np.transpose(T(3))))

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [17]:
np.dot(T(3),np.array([111,112,121,122,211,212,221,222]))

array([111.+0.j, 121.+0.j, 211.+0.j, 221.+0.j, 112.+0.j, 122.+0.j,
       212.+0.j, 222.+0.j])

In [18]:
np.dot(np.dot(T(3),Sz(0,3)),np.transpose(T(3)))-Sz(1,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [19]:
np.dot(np.dot(T(3),Sz(1,3)),np.transpose(T(3)))-Sz(2,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [20]:
np.dot(np.dot(T(3),Sz(2,3)),np.transpose(T(3)))-Sz(0,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [21]:
np.dot(np.dot(T(3),Sx(0,3)),np.transpose(T(3)))-Sx(1,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [22]:
np.dot(T(3),np.dot(T(3),T(3)))

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [23]:
np.dot(T(3),H(1,1,1,3))-np.dot(H(1,1,1,3),T(3))

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

### Now let us take a look at constructing eigenstates of T

In [24]:
psi_a = qi.Statevector.from_label("000").data
psi_b = qi.Statevector.from_label("100").data
psi_c = qi.Statevector.from_label("110").data
psi_d = qi.Statevector.from_label("111").data

In [25]:
def bkt(psi_a,psi_b):
    return np.dot(np.conjugate(psi_a),psi_b)

def psi_k(psi,m,L):
    k = m*2*np.pi/(L)
    psi_l = [psi]
    for r in range(1,L):
        psi_l.append(np.exp(-1j*k)*np.dot(T(L),psi_l[r-1])) 
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out

In [26]:
m=0
L=3
psi = psi_d
np.exp(-1j*m*2*np.pi/(L))*np.dot(T(3),psi_k(psi,m,L))-psi_k(psi,m,L)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [27]:
print( bkt(psi_k(psi_b,1,3),psi_k(psi_b,1,3)) ) 

(1.0000000000000002+0j)


In [28]:
print( bkt(psi_k(psi_b,-1,3),psi_k(psi_b,1,3)) ) 
print(psi_k(psi_b,-1,3))
print(psi_k(psi_b,1,3))

(2.220446049250313e-16-2.220446049250313e-16j)
[ 0.        +0.00000000e+00j -0.28867513-5.00000000e-01j
 -0.28867513+5.00000000e-01j  0.        +0.00000000e+00j
  0.57735027-9.62250449e-12j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j]
[ 0.        +0.00000000e+00j -0.28867513+5.00000000e-01j
 -0.28867513-5.00000000e-01j  0.        +0.00000000e+00j
  0.57735027-9.62250449e-12j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j]


In [29]:
print( bkt(psi_k(psi_b,-1,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_b,0,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_a,0,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_c,1,3),psi_k(psi_b,1,3)) )
print( bkt(psi_k(psi_c,-1,3),psi_k(psi_c,1,3)) )
print( bkt(psi_k(psi_c,0,3),psi_k(psi_c,1,3)) )
print( bkt(psi_k(psi_d,0,3),psi_k(psi_b,1,3)) ) 

(2.220446049250313e-16-2.220446049250313e-16j)
(-5.551115122964224e-17-1.1102230246332345e-16j)
0j
0j
(2.220446049250313e-16-2.220446049250313e-16j)
(-5.5511151229579464e-17-1.1056263373709945e-16j)
0j


There is a state for each occupancy number. 

### Now let's try to write the Hamiltonian

In [34]:
import scipy.linalg as lng

In [35]:
H3 = H(1,1.2,1.5,3)

(e3, psi3) = lng.eig(H3)
e3

array([ 2.82822021+0.j,  4.57177979+0.j, -3.7       +0.j,  4.57177979+0.j,
        2.82822021+0.j, -3.7       +0.j, -3.7       +0.j, -3.7       +0.j])

In [36]:
def exv(psi_a,O,psi_b):
    return np.dot(np.conjugate(psi_a),np.dot(O,psi_b))

In [37]:
psi_occ = [psi_a,psi_b,psi_c,psi_d]

def Ok(O,m):
    Oc = []
    for i in range(0,len(psi_occ)):
        Or = []
        for j in range(0,len(psi_occ)):
            psi_i = psi_k(psi_occ[i],m,L)
            psi_j = psi_k(psi_occ[j],m,L)
            if max(np.abs(psi_i)) > 10**(-8) and max(np.abs(psi_j)) > 10**(-8):
                oij = exv(psi_i,O,psi_j)
                Or.append(oij)
        if len(Or) > 0:
            Oc.append(Or)
    return np.array(Oc)

Check Eigenvalues

In [38]:
(ek0,psi_k0) = lng.eig(Ok(H3,0))
(ek1,psi_k1) = lng.eig(Ok(H3,1))
(ek2,psi_k2) = lng.eig(Ok(H3,2))

In [39]:
print(ek0)
print(ek1)
print(ek2)

[2.82822021+0.j 4.57177979+0.j 4.57177979+0.j 2.82822021+0.j]
[-3.7-1.11022302e-16j -3.7-1.31398730e-17j]
[-3.7+0.00000000e+00j -3.7-2.62062492e-17j]


In [40]:
e3

array([ 2.82822021+0.j,  4.57177979+0.j, -3.7       +0.j,  4.57177979+0.j,
        2.82822021+0.j, -3.7       +0.j, -3.7       +0.j, -3.7       +0.j])

In [41]:
pd.DataFrame(Ok(H3,0))

0         1         2         3
0  3.0+0.0j  0.0+0.0j -0.5+0.0j  0.0+0.0j
1  0.0+0.0j  4.4+0.0j  0.0+0.0j -0.5-0.0j
2 -0.5-0.0j  0.0+0.0j  4.4+0.0j  0.0+0.0j
3  0.0+0.0j -0.5+0.0j  0.0+0.0j  3.0+0.0j

Notice that parity is perserved

## Next let us try to include parity in our decomposition

In [42]:
#Construct the parity operator

def P(L):
    p = I0(L)
    for i in range(0,L):
        p = np.dot(Sz(i,L),p)
    return p

In [43]:
P(2)

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j]])

In [44]:
print(exv(psi_a,P(3),psi_a))
print(exv(psi_b,P(3),psi_b))
print(exv(psi_c,P(3),psi_c))
print(exv(psi_d,P(3),psi_d))

(1+0j)
(-1+0j)
(1+0j)
(-1+0j)


### Special case when $k = 0, \pi$

In this case we can use $|a(k,p)> = \frac{1}{N}\sum_{r=0}^{L-1}e^{-ikr}T^r(1+pP)|a>$

In [45]:
def Mdot(Ol):
    m = Ol[0]
    for i in range(1,len(Ol)):
        m = np.dot(Ol[i],m)
    return m

def psi_kp(psi,m,p,L):
    k = m*2*np.pi/(L)
    psi_l = [Mdot([I0(L)+p*P(L),psi])]
    for r in range(1,L):
        psi_l.append(np.exp(-1j*k)*Mdot([T(L),psi_l[r-1]])) 
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out    

In [46]:
p = -1
n = 1
psi  = psi_b
Mdot([P(3),psi_kp(psi,n,p,3)])-p*psi_kp(psi,n,p,3)


array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

The above representation is not supposed to work for $n \neq 0,\pi$, however, it seems to work for me.  Perhaps this is something special with L=3.  The problem is supposed to be that $P |a(k,p)> = p |a(-k,p)>$

In [47]:
Mdot([P(L),T(L)])-Mdot([T(L),P(L)])  #This is not supposed to be true.  It seems they are calling reflection symmetary parity 

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

## Reflection symmetary

In [48]:
def R(L):
    r = I0(L)
    for i in range(0,int(L/2)):
        exc = Exchange(i,L-1-i,L)
        r = np.dot(exc,r)
    return r
        

In [49]:
Mdot([R(L),T(L)])-Mdot([lng.inv(T(L)),R(L)])  #This makes since.  In the papaer, R is called P

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

### Special case when 𝑘=0,𝜋

In this case we can use |𝑎(𝑘,𝑝)>=1𝑁∑𝐿−1𝑟=0𝑒−𝑖𝑘𝑟𝑇𝑟(1+𝑝𝑃)|𝑎>

In [50]:
def psi_kp(psi,m,p,L):
    k = m*2*np.pi/(L)
    psi_l = [Mdot([I0(L)+p*R(L),psi])]
    for r in range(1,L):
        psi_l.append(np.exp(-1j*k)*Mdot([T(L),psi_l[r-1]])) 
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out   

In [51]:
p = 1
n = 1
psi  = psi_c
Mdot([R(3),psi_kp(psi,n,p,3)])-p*psi_kp(psi,-n,p,3)

array([ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  3.33066907e-16-2.22044605e-16j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00-3.84592537e-16j,
       -3.33066907e-16-1.66533454e-16j,  0.00000000e+00+0.00000000e+00j])

Okay now we have the expected results.  We have $R|𝑎(𝑘,𝑝)> = p |𝑎(-𝑘,𝑝)>$ as long as $k = \frac{2 n \pi}{L}$

### Semi-momentum states

instead of $e^{i k r}$ we use $\cos(k r)$ or $\sin(k r)$

In [52]:
def Ck(s,k):
    if s == 1:
        ck = np.cos(k)
    elif s == -1:
        ck = np.sin(k)
    else:
        raise Exception("s must be +1 or -1")
    return ck
    

def psi_sk(psi,s,m,L):
    k = m*2*np.pi/(L)
    psi_l = [psi]
    for r in range(1,L):
        psi_l.append(Mdot([T(L),psi_l[r-1]])) 
    for r in range(0,L):
        psi_l[r] = Ck(s,k*r)*psi_l[r]
    #Normalizing
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out   

In [53]:
n=1
np.amax(psi_k(psi_c,n,3)-(psi_sk(psi_c,1,n,3)+1j*psi_sk(psi_c,-1,n,3))/np.sqrt(2))

(8.333611578592581e-12-4.811429032969272e-12j)

In [54]:
bkt(psi_sk(psi_c,1,n,3),psi_sk(psi_c,-1,n,3))

(2.7755575615628914e-16-3.2311742677852644e-27j)

### Semi-momentum with reflection

In [55]:
def psi_skp(psi,s,m,p,L):
    k = m*2*np.pi/(L)
    psi_l = [psi]
    for r in range(1,L):
        psi_l.append(Mdot([T(L),psi_l[r-1]])) 
    for r in range(0,L):
        psi_l[r] = Ck(s,k*r)*Mdot([I0(3)+p*R(L),psi_l[r]])
    #Normalizing
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out  

In [56]:
s = -1
n = 1
p = -1


Mdot([R(3),psi_skp(psi_c,s,n,p,3)])-p*psi_skp(psi_c,s,n,p,3)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

These are eigenstates of parity.  Notice that sates with different s are not orthogonal and states with opposite n are not orthogonal

In [57]:
print( bkt(psi_skp(psi_c,s,n,p,3),psi_skp(psi_c,-s,n,p,3)) )
print( bkt(psi_skp(psi_c,s,n,p,3),psi_skp(psi_c,s,-n,p,3)) )
print( bkt(psi_skp(psi_c,s,n,p,3),psi_skp(psi_c,s,n,-p,3)) )

print( bkt(psi_skp(psi_c,s,0,p,3),psi_skp(psi_c,s,1,p,3)) )
print( bkt(psi_skp(psi_c,s,0,p,3),psi_skp(psi_c,s,1,-p,3)) )

(1+2.222222222222225e-11j)
(-1.0000000000000002+0j)
0j
0j
0j


Let's try to build the basis

In [58]:
psi_a = qi.Statevector.from_label("000").data
psi_b1 = qi.Statevector.from_label("100").data
psi_b2 = qi.Statevector.from_label("010").data
psi_b3 = qi.Statevector.from_label("001").data
psi_c1 = qi.Statevector.from_label("110").data
psi_c2 = qi.Statevector.from_label("101").data
psi_c3 = qi.Statevector.from_label("011").data
psi_d = qi.Statevector.from_label("111").data

psi_all = [psi_a,psi_b1,psi_b2,psi_b3,psi_c1,psi_c2,psi_c3,psi_d]


s = 1
psi_sem = []
for n in range(0,len(psi_all)):
    for m in range(0,2):
        for pi in range(0,2):
            p = 1 - 2*pi
            psi_tst = psi_skp(psi_all[n],s,m,p,3)
            tst = 0
            for i in range(0,len(psi_sem)):
                tst += bkt(psi_tst,psi_sem[i])
            if np.abs(tst) < 10**(-10) and np.abs(np.amax(psi_tst)) > 10**(-10):
                print(n,m,p)
                psi_sem.append(psi_tst)

0 0 1
1 0 1
1 1 1
1 1 -1
4 0 1
4 1 1
4 1 -1
7 0 1


In [59]:
len(psi_sem)

8

## Spin

what I originally called parity they call Z

In [60]:
def Z(L):
    z = I0(L)
    for i in range(0,L):
        z = np.dot(Sz(i,L),z)
    return z

In [61]:
def psi_kz(psi,m,z,L):
    k = m*2*np.pi/(L)
    psi_l = [Mdot([I0(L)+z*Z(L),psi])]
    for r in range(1,L):
        psi_l.append(np.exp(-1j*k)*Mdot([T(L),psi_l[r-1]])) 
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out    

In [65]:
n = 1
z = -1
psi = psi_b
Mdot([Z(3),psi_kz(psi,n,z,3)])+psi_kz(psi,n,z,3)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

### Now we can put it all together

In [67]:
def psi_skpz(psi,s,m,p,z,L):
    k = m*2*np.pi/(L)
    psi_l = [psi]
    for r in range(1,L):
        psi_l.append(Mdot([T(L),psi_l[r-1]])) 
    for r in range(0,L):
        psi_l[r] = Ck(s,k*r)*Mdot([I0(3)+p*R(L),I0(L)+z*Z(L),psi_l[r]])
    #Normalizing
    psi_out = sum(psi_l)
    psi_out = psi_out/np.sqrt(bkt(psi_out,psi_out)+10**(-10)*1j)  #I use +10**(-10)*1j to avoid dividing by zero
    return psi_out  

In [73]:
s = 1
n = 1
p = -1
z = -1
psi = psi_b

print(psi_skpz(psi_b,s,n,p,z,3))
print(Mdot([Z(3),psi_skpz(psi_b,s,n,p,z,3)])-z*psi_skpz(psi_b,s,n,p,z,3))
print(Mdot([R(3),psi_skpz(psi_b,s,n,p,z,3)])-p*psi_skpz(psi_b,s,n,p,z,3))

[ 0.        +0.0000000e+00j -0.70710678+1.9641855e-12j
  0.        +0.0000000e+00j  0.        +0.0000000e+00j
  0.70710678-1.9641855e-12j  0.        +0.0000000e+00j
  0.        +0.0000000e+00j  0.        +0.0000000e+00j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


These are eigenstates of R and Z