In [1]:
import numpy as np

In [2]:
f = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [22]:
def r(i,j,a,b):
    ro = np.identity(4)
    ro[i,i] = a
    ro[j,j] = a
    ro[i,j] = b
    ro[j,i] = b
    return ro

f1 = np.dot(r(1,2,f[1,1],-f[2,1]),f)
print(f1)
f2 = np.dot(r(1,3,f1[1,1],-f1[3,1]),f1)
print(f2)
f3 = np.dot(r(0,3,f2[0,0],-f2[3,0]),f2)
print(f3)

[[  1.   2.   3.   4.]
 [-60. -64. -68. -72.]
 [  4.   0.  -4.  -8.]
 [ 13.  14.  15.  16.]]
[[ 1.000e+00  2.000e+00  3.000e+00  4.000e+00]
 [ 3.658e+03  3.900e+03  4.142e+03  4.384e+03]
 [ 4.000e+00  0.000e+00 -4.000e+00 -8.000e+00]
 [ 8.000e+00  0.000e+00 -8.000e+00 -1.600e+01]]
[[-6.300e+01  2.000e+00  6.700e+01  1.320e+02]
 [ 3.658e+03  3.900e+03  4.142e+03  4.384e+03]
 [ 4.000e+00  0.000e+00 -4.000e+00 -8.000e+00]
 [ 0.000e+00 -1.600e+01 -3.200e+01 -4.800e+01]]


In [23]:
r(0,3,f2[0,0],-f2[3,0])

array([[ 1.,  0.,  0., -8.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-8.,  0.,  0.,  1.]])

In [24]:
f2

array([[ 1.000e+00,  2.000e+00,  3.000e+00,  4.000e+00],
       [ 3.658e+03,  3.900e+03,  4.142e+03,  4.384e+03],
       [ 4.000e+00,  0.000e+00, -4.000e+00, -8.000e+00],
       [ 8.000e+00,  0.000e+00, -8.000e+00, -1.600e+01]])

In [46]:
ry = 1/np.sqrt(2)*np.array( [[1,1,0,0],[-1,1,0,0],[0,0,1,1],[0,0,-1,1]] )
rym = 1/np.sqrt(2)*np.array( [[1,-1,0,0],[1,1,0,0],[0,0,1,-1],[0,0,1,1]] )
cx = np.array( [[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]] )
np.dot(ry,np.dot(cx,rym))

array([[ 1.00000000e+00,  2.23711432e-17,  0.00000000e+00,
         0.00000000e+00],
       [ 2.23711432e-17,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        -2.23711432e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.23711432e-17,
        -1.00000000e+00]])

In [49]:
z1 = np.array( [[1,0,0,0],[0,-1,0,0],[0,0,1,0],[0,0,0,-1]] )
z2 = np.array( [[1,0,0,0],[0,1,0,0],[0,0,-1,0],[0,0,0,-1]] )

z1+z2

array([[ 2,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, -2]])

In [59]:
1/2*(np.identity(4) - np.dot(z1,z2) + z1+ z2)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [61]:
np.dot((np.identity(4)+1j*z1),(np.identity(4)+1j*z2))

array([[0.+2.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-2.j]])